server:
  port: 8080

spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  #datasource:
    #url: jdbc:h2:file:./db/shareit
    #username: test
    #password: test
    #driverClassName: org.h2.Driver

  datasource:
    url: jdbc:postgresql://localhost:5432/shareitdb
    username: shareit
    password: shareit
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: DEBUG
      transaction:
        interceptor: TRACE
        transaction.interceptor: TRACE